name: My trial pipeline
on:
  push:

jobs:
  echo_the_date:
  runs-on: ubuntu-latest
  steps:
  - name: echo the date
    run: echo "The current time and date is $(date)"
  - name: echo the current branch
    run: echo ${{ github.ref_name }}

    test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_API: ${{ secrets.OPENWEATHERMAP_API }}
    steps:
    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # maven
    name: Setup maven
    uses: stCarolas/setup-maven@4.3
    with:
      maven-version: 3.8.2
    
    #
    #- name: checkout source
    #  uses: a

